### ISSUE TITLE
Amplify is totally crashed because of the Window is not defined error in youtube-iframe package

### ISSUE THREAD

**Issue by svenkatesh-nyros** [aws-amplify/amplify-js#3506]
@powerful23, @robbevan ,@mlabieniec, @jordanranz, @mbahar, @richardzcode
After installation of the @aws-amplify with the additional package of youtube-iframe.

Getting the error of window is not defined in

1. node_modules/youtube-iframe/index.js 50:3
2. node_modules/@aws-amplify/ui/dist/aws-amplify-ui.js:1

**Can you please provide the previous working version without facing the issue of window is not defined in the following folders.**

![1](https://user-images.githubusercontent.com/16791299/59894079-df5d8300-93fc-11e9-9ade-561167eb9cc6.png)
![2](https://user-images.githubusercontent.com/16791299/59894080-dff61980-93fc-11e9-9f0b-5c3c62f3bc15.png)

**Comment by johnhamelink** [comment]
We're also experiencing this - we're using amplify as the basis for a nodejs SDK we're building, and upgrading from 1.1.27 to 1.1.29 produces this error for this. To add insult to injury, there's no changelog to be found, so it wasn't clear what caused this without looking into the codebase!

- **Please do:** use semantic versioning properly so that we can upgrade this package in confidence - this should've been a minor upgrade as you introduced new packages which changed base requirements of the library.
- **Please do:** seriously consider adding a changelog so that other libraries which depend on this can track changes more easily.
- **Please don't:** assume that this library is only being used in the browser

**Comment by mlabieniec** [comment]
amplify-js is specifically a client / mobile / web library and does not have official support for node.js. For the iframe issue, we are aware of an issue/bug in analytics that should fix this in: https://www.npmjs.com/package/@aws-amplify/analytics/v/1.2.18-unstable.0

@svenkatesh-nyros can you give this version a try and see if this fixes your issue. We will review this and make sure we add this case to our integration tests.

On the subject of node.js, we can add some documentation around how to get things working properly in node (via isomorphic fetch etc.), but at the moment our team efforts are focused on mobile/web client use cases. We are however investigating node support specifically for SSR.

**Comment by johnhamelink** [comment]
@mlabieniec we ended up stripping out all of amplify and replacing it with *just* `@aws-amplify/auth` - we're only using amplify to gain Cognito user credentials we can use to access other AWS products with.

**Comment by ajhool** [comment]
Amplify has repeatedly said that there is no official support for nodejs, but that amplify _is moving towards supporting node.js officially_. The Amplify team has repeatedly said that Amplify is moving towards SSR support (or, at least, not breaking on the server -- even if it doesn't actually render on the server). Many of us are using limited versions of Amplify on the server and are aware that it does not currently officially support non-browser environments, but we didn't expect the problem to get worse over time -- it was supposed to get better.

For anybody with this problem, my resolution for similar issues with this package was to dynamically import amplify on the client side via a dynamic import in `onComponentDidMount`.

**Comment by aldegoeij** [comment]
@mlabieniec understanding of the mobile/web focus, however e.g. `gatsby build` for generating static web site is currently breaking as amplify on import of youtube-iframe is not defining window.

**Comment by aldegoeij** [comment]
@mlabieniec issue still exists on `aws-amplify@1.1.30-unstable.1` and `aws-amplify-react@2.3.10-unstable.1`

**Comment by ajhool** [comment]
@manueliglesias was this issue resolved or considered a no-fix?

**Comment by aldegoeij** [comment]
referencing tickets #3486, #3506, #3615, #3015, #876, #3477 and webpack/webpack#6522
