### ISSUE TITLE
Update Mutation JS function removes fields when not provided as arguments

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws-amplify/amplify-js#3541]
**Describe the bug**
When using the UpdateItem resolver as mentioned in (https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-resolvers.html#modifying-the-updatepost-resolver-dynamodb-updateitem) that only updates the fields that a provided, I am running in different behaviour.
When I run it from AWS Query:
```
mutation UpdatePost() {
  updatePost(
    pk: "a6a706f9-619d-4400-af4e-f5925ac851af",
    sk: "POST", 
    status: PUBLISHED, 
    expectedVersion: 0) {
  	pk
    title
    content
    status
  }
}
```
then I expect my Post which also has a Title and a Content field, to change from status DRAFT to PUBLISHED.
This is also what happens and the title and content field are still there.

When I use the generated API Service in Angular, and run the same Update, it does update the Status to PUBLISHED but it removes the title and content.
Since I didn't provided title & content, I expected these fields to be untouched.
I believe that the value might be passed in as NULL which triggers the Resolver to remove them.

The auto generated API call looks like: 
```
  async UpdatePost(
    pk: string,
    sk: string,
    expectedVersion: number,
    status?: PostStatus,
    title?: string,
    content?: string,
    dateUpdated?: string
  ): Promise<UpdatePostMutation> {
    const statement = `mutation UpdatePost($pk: ID!, $sk: String!, $expectedVersion: Int!, $status: PostStatus, $title: String, $content: String, $dateUpdated: AWSDateTime) {
        updatePost(pk: $pk, sk: $sk, expectedVersion: $expectedVersion, status: $status, title: $title, content: $content, dateUpdated: $dateUpdated) {
          __typename
          pk
          type
          title
          content
          readConfirmation
          thread
          created
          updated
          version
          currentVersion
          status
        }
      }`;
    const gqlAPIServiceArguments: any = {
      pk,
      sk,
      expectedVersion
    };
    if (status) {
      gqlAPIServiceArguments.status = status;
    }
    if (title) {
      gqlAPIServiceArguments.title = title;
    }
    if (content) {
      gqlAPIServiceArguments.content = content;
    }
    if (dateUpdated) {
      gqlAPIServiceArguments.dateUpdated = dateUpdated;
    }
    const response = (await API.graphql(
      graphqlOperation(statement, gqlAPIServiceArguments)
    )) as any;
    return <UpdatePostMutation>response.data.updatePost;
  }
```

I try to debug it or I have to dynamically build up the GrahpQL mutation so that it omits the fields that are not used?

**update**:
Commenting the expRemove lines did result in the title and content not to be removed, however it is not a fix.
```
    ## Iterate through each argument, skipping "pk", "sk" and "expectedVersion" **
    #foreach( $entry in $context.arguments.entrySet() )
        #if( $entry.key != "pk" && $entry.key != "sk" && $entry.key != "expectedVersion" )
            #if( (!$entry.value) && ("$!{entry.value}" == "") )
                ## If the argument is set to "null", then remove that attribute from the item in DynamoDB **
                
                ## COMMENTING OUT THESE 2 LINES REMIED THE ISSUE, BUT IT's NOT A SOLUTION
                ## #set( $discard = ${expRemove.add("#${entry.key}")} )
                ## $!{expNames.put("#${entry.key}", "$entry.key")}
            #else
                ## Otherwise set (or update) the attribute on the item in DynamoDB **

                $!{expSet.put("#${entry.key}", ":${entry.key}")}
                $!{expNames.put("#${entry.key}", "$entry.key")}
                $!{expValues.put(":${entry.key}", { "S" : "${entry.value}" })}
            #end
        #end
    #end

```

Looking at the request from Angular going to Appsync:

CreatePost
```
"mutation CreatePost($type: PostTypes!, $title: String!, $content: String, $readConfirmation: Boolean, $thread: Boolean, $status: PostStatus!) {
  createPost(type: $type, title: $title, content: $content, readConfirmation: $readConfirmation, thread: $thread, status: $status) {
    __typename
    pk
    type
    title
    content
    readConfirmation
    thread
    created
    updated
    version
    currentVersion
    status
  }
}
"
// variables:
{type: "POST", title: "ddd", status: "DRAFT", content: "ssss"}
```
UpdatePost:
```
"mutation UpdatePost($pk: ID!, $sk: String!, $expectedVersion: Int!, $status: PostStatus, $title: String, $content: String) {
  updatePost(pk: $pk, sk: $sk, expectedVersion: $expectedVersion, status: $status, title: $title, content: $content) {
    __typename
    pk
    type
    title
    content
    readConfirmation
    thread
    created
    updated
    version
    currentVersion
    status
  }
}
"
// variables
{pk: "9d58d914-9336-47e3-b62b-1d65efe4d7e0", sk: "POST", expectedVersion: 0, status: "PUBLISHED"}
```

So it kind a confirms my suspicion that because $title and $content are mentioned but no value is provided, it is considered as a NULL value and therefor removed.

The problem is I can't see how it the request comes into the Resolver. When I run a test in the Appsync console, I can leave the `title` field out and I do not see the REMOVE command, unless I add `title` with the value `null`.

So the only solution I see now is to build up the updatePost mutation params based on what fields are provided in the JS function.

**Comment by mattiLeBlanc** [comment]
For Now I fixed in my JS GraphQL function by dynamically building up the graphql fields in the mutation:
```
  async UpdatePost2(params: UpdatePostPayload): Promise<UpdatePostMutation> {
    const types = {
      pk: 'ID!',
      sk: 'String!',
      expectedVersion: 'Int!',
      status: 'PostStatus',
      title: 'String',
      content: 'String',
    }
    let definition = '', mapping = '';
    
    Object.keys(params).forEach( (key: string, i: number) => {
      if (types[key]) {
        definition += `$${key}: ${types[key]}${i < Object.keys(params).length-1 ? ', ': ''}`;
        mapping += `${key}: $${key}${i < Object.keys(params).length-1 ? ', ': ''}`;
      }
    });
    const statement = `mutation UpdatePost(${definition}) {
        updatePost(${mapping}) {
          __typename
          pk
          type
          title
          content
          readConfirmation
          thread
          created
          updated
          version
          currentVersion
          status
        }
      }`;

    const response = (await API.graphql(
      graphqlOperation(statement, params)
    )) as any;
    return <UpdatePostMutation>response.data.updatePost;
  }
```

**Comment by tw1t611** [comment]
I ran into an similar issue, since I have fields in my schema, where "" should be a valid value and the field should not be removed.

**Comment by jordanranz** [comment]
Hey @mattiLeBlanc, are you still experiencing this issue?

Also, is any part of this issue related to the Amplify library?

**Comment by mattiLeBlanc** [comment]
@jordanranz  I haven't verified with the latest Amplify library. Has there been any update to the Graphql lib that could resolve this?

**Comment by sammartinez** [comment]
@mattiLeBlanc I apologize on behalf of the team in the delay to yourself. There has been work in order to resolve this issue. Can you verify you are still experiencing the issue on your side ?

**Comment by mattiLeBlanc** [comment]
I have seen the issue happen yet in case we send in a null value for a key. But we try not to send such statement.

**Comment by cyrfer** [comment]
@sammartinez I am seeing similar problems. Any fields I do not specify in the update result in other fields being removed from my data.

Using amplify cli 4.18.0.

**Comment by krakrak** [comment]
Hello, I'm  having the same issue, even when testing with the AWS Appsync console. In the logs $context.arguments doesn't have the values that are removed in the request template
