### ISSUE TITLE
Removing Social federatedSignIn Cookie

### ISSUE THREAD

**Issue by saaniaki** [aws-amplify/amplify-js#3933]
** Which Category is your question related to? **
Social federatedSignIn, Remember Me feature

** What AWS Services are you utilizing? **
Cognito, amplify auth

** Provide additional details e.g. code snippets **
My end goal is to create a remember me feature for my application. Since this feature is not supported by Amplify yet, I am trying to write it myself.

I have managed to create this feature for username and password login, I just ask the user if they want to be remembered and then I set the Auth Storage to localStorage, if not, I set it to sessionStorage:

```
    const rememberMe = localStorage.getItem('remember-oauth');
    if (rememberMe === 'true') {
      Auth.configure({
        storage: localStorage
      });
    } else {
      Auth.configure({
        storage: sessionStorage
      });
    }
```

This works for all scenarios, other than one exception. If the user logs in with Google, and I set the storage to 'sessionStorage'. In this case, if the user forgets to log out and closes the window, all the records in sessionStorage will be removed by the browser as expected and next time, my application will show the login page since it can not retrieve the user. 

Then, as soon as the user tries to login via Google, i.e:
`Auth.federatedSignIn({provider: CognitoHostedUIIdentityProvider.Google})`
a  network call would go to https://<mydomain>/oauth2/authorize. so far so good.

At this point, I expect to see the OAuth log in page from google where the user can choose an account and log in, like the first time. However, Cognito gets back to the app with the JWT!

This is while there are no localStorage, sessionStorage or cookie records on the browser. I've tried to debug and I've seen the network transmissions. What I've found out is that the request to the '/oauth2/authorize' endpoint has a cookie header set to a value like this:

`
cookie: cognito-fl="W10="; XSRF-TOKEN=f89f6339-5b67-4321-a5b0-cb39e1aad647; cognito="H4sIAAAAAAAAAA3QRbKjUAAAwBNRhcvscIK7bShC4OHup//TR+h3rkhmM1nUk9nN4U3r2D9kQPtbDCZL7p6Fh3+L4uyEbSROGGf2ivsVlkbX11BIo6hKlobmWPiBk6aQwzcZKlRtxyOro3hqB4er2amnkJg+AHConganWp5aHdzIqFd+vDM9NDE9NtPBEtovC01i6A7OIJnu5FqxTZ6MbNQ4Pb9YpxLXUJtDURMriLec9qvMrJLhTb6wflD96y3N/NXro37UpF00Ykgb6onRXKBGhG323nSFZOxpXzgjU4bYSCDHoYUu/td2nRfeqCfQs7bPEZcyiHJRMCu2sZimioTuNc8F0/hhzU7iu8oyyMpYJ0ma+5Q7QjsPb8/Zx3CUE37dQuEjJacKBLRhaxashng+1pTmtAW3W3s/hADTjYPuxDe3YHopqxm1518rDByOaFHfU4VziwUPq37b8R8p1DMlweG9Zltbb/OUsPWaU1axyKpjW2Zi5WK1D8MtQPfMzQpJBW06UGL7snjRSoQNGm/nGW34XpjzHDom0oIsIvwlJNDYvbMklGJpYQiYlRx0Dffs3dITAb6fhD4j3XHD+XwNP0dxnXNNZQ9cacFEgKSIrQJOkTDNJJPbal7srWHshhxvOXoM0hsd6SaCBxcOLHGv/TCHvytZkEFF6PZrji+cvPoXjUdbfiwRfA2Rq6pwJmown22wrMg0EaVnBKUr0En7pPqzkqj/zbns364R/NaWKMu3rfhVDg4hlAp16Qgrk8uIzPztOyUf2iGwOooGftNZDTPWXjLY2PsxYK/HrAvuX/ZthlHx8aFDSH8l8Utx4+Vj7BDI9c+0AjqMoUI5Hm1Av4a3T/rSt1v1D/0Dn87C0jIDAAA="
`

I assume the application somehow managed to tell Cognito about the previously logged in user although there are no localStorage, sessionStorage or cookie records on the browser.

Please help me to somehow prevent this behavior. I want to be able to manually remove this cookie and prevent sending it to Cognito.

**Comment by rafaeltc** [comment]
I am facing the same issue with federated sign in on microsoft (azure) AD. After signing out, the login requests still carry the cognito cookie and therefore I am never truly signed out nor redirected to the federated sign in page. As a result, the user is always signed in.

**Comment by naticaceres** [comment]
I am getting the same behavior as @rafaeltc 
I am using angular and storing in memory the auth cookies, following this guideline

https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-security-tokens

So far it has been a bumpy road. 
I can't get plenty of Auth methods to work, Auth.signOut() doesn't seem to return anything ever, it doesn't fail, but it doesn't successfully complete either.

Are there any workarounds to this issue?

**Comment by xai1983kbu** [comment]
@saaniaki I can find cookies by clicking the button "view site information" which located right before URL
![cookies_cognito](https://user-images.githubusercontent.com/14042193/83378346-2875cf80-a3e1-11ea-9df2-073bd9f19d5e.png)

beside Cognito pool's domain cookies I can see Facebook's domain cookies
![cookies](https://user-images.githubusercontent.com/14042193/83378617-ec8f3a00-a3e1-11ea-8df0-fb07cfd1935b.png)

If I delete only cookie - "cognito" and try to Login with Facebook next time then the same user logins without the claim of password entering (I would call it - an infinite loop of one user login).

But if I delete all Facebook's domain cookies and one Cognito pool's domain cookie - "cognito" and try to Login with Facebook then the claim of password entering is appearing (that what I want to). 
![cookies_facebook](https://user-images.githubusercontent.com/14042193/83379863-388fae00-a3e5-11ea-8907-8e231419263e.png)

In my logout function, I use these two methods
- [cognitoUser.globalSignOut()](https://github.com/aws-amplify/amplify-js/blob/55441243f73ab56ed1611e4beed3c7919500412f/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1925)
- [cognitoUser.signOut()](https://github.com/aws-amplify/amplify-js/blob/55441243f73ab56ed1611e4beed3c7919500412f/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1950)

if I add code below to my logout function (I think that method is mentioned in [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html))
window.location = `https://${cognito_user_pool}/logout?client_id=${cognito_client_id}&logout_uri=https://localhost:3000/register` then in  Cognito pool's domain cookies appears - "cognito_fl"  (it presents in @saaniaki example)

Cite @yuntuowang in this issue https://github.com/amazon-archives/amazon-cognito-auth-js/issues/68
I get your point. Basically, since once you click sign-out, google cookie won't be cleared. So you won't be redirected to the google page to choose an account to sign in.

It seems the idea of deleting cookie is clear but how to do it in the right way?

I have one more method in mind  - delete user from the Facebook app in lambda function. 
Is it possible if we have userId on Facebook, Facebook appId and Facebook app secret?

**Comment by xai1983kbu** [comment]
I found the related question without an answer
https://stackoverflow.com/questions/50623919/aws-cognito-with-google-federated-identity-logs-me-in-with-the-last-user

**Comment by xai1983kbu** [comment]
Next step of cookies exploring revealed some useful information (at least for me).

If my logout function runs next line of code:
`window.location = https://${AUTH_DOMAIN}/logout?client_id=${cognito_client_id}&logout_uri=https://localhost:3000/register`
then Cognito pool's domain cookie - "cognito" will be invalidated by changing expiration datetime:
a) for the first logout (running my logout function) after login by setting value of Expires on 1 January 1970
![coognito_cookie_time_logout_first_time](https://user-images.githubusercontent.com/14042193/83445682-16824400-a456-11ea-92da-a69dbcde227d.png)
b) for the next logouts after login by setting the same date and time for Created and Expires
![coognito_cookie_time_logout_](https://user-images.githubusercontent.com/14042193/83445543-d91db680-a455-11ea-950b-dd77b3852cc9.png)

With invalidated Cognito pool's domain cookie - "cognito" I only needed to clear or invalidate facebook cookies (or maybe only one of them).

It seems It's not allowed to delete cookies from another domain https://stackoverflow.com/a/14314117/9783262
So, the invalidation of facebook cookies only remains. I think this answer https://stackoverflow.com/a/8828365/9783262 

> Yes, I ran into this same issue myself. Dont do logout.php or JS SDK's FB.logout(). Rather call the Graph API with an HTTP Delete command to me/permissions. That will kill the access token, remove the app from the user's app listing and maintain their browser's cookie for facebook. You can call it either server side or client side. Here's the client side Javascript SDK way:
> 
> FB.api("me/permissions","delete", function(response){/*do something if you want*/})

will lead to a solution.
It would be nice to trigger a lambda function that does this job for me. I didn't found a post-signout trigger but I think the post-authentication trigger can be used.

**Comment by xai1983kbu** [comment]
I managed to de-authorize an application after that facebook application goes to the tab - "Removed"
![app_remove](https://user-images.githubusercontent.com/14042193/83600449-49702900-a577-11ea-94de-672508d28bdb.png)
I used facebook sdk for javascript:
![facebook_sdk](https://user-images.githubusercontent.com/14042193/83602242-d7014800-a57a-11ea-964e-3a8921de9fe6.png)
and next code:
```
  const handleRevokeFacebookPermissions = () => {
    window.FB.getLoginStatus(function (response) {
      console.log(response)
      if (response.status === 'connected') {
        window.FB.api('me/permissions', 'delete', function (response) {
          console.log('delete permission ')
        })
      }
    })
  }
```
I put "handleRevokeFacebookPermissions" function at the end of login process. So, after a user enters email and password an application will be added to tab -  "Active", see picture above, but after "handleRevokeFacebookPermissions" function runs our application will be moved to tab "Removed".

One, nuance: window.FB.getLoginStatus won't return response.status === 'connected' even when user exists in facebook domain cookies if exists valid cookie "fblo_<appId>"on your domain (or localhost) https://stackoverflow.com/q/44705792/9783262
In my case, cookie "fblo_<appId>" is always expired. 
![fblo_appid](https://user-images.githubusercontent.com/14042193/83601850-17ac9180-a57a-11ea-90f3-0aa6db5de403.png)

Now, when I click "Login with facebook" again user will see next screen
![facebook_continue](https://user-images.githubusercontent.com/14042193/83602601-8b9b6980-a57b-11ea-9fb5-e99faf855a9d.png)

Users will see that there is no way to choose another user and she or he will understand that to be save there is no choice except to click one more button "Logout from Facebook" which I am going allocate in my web app too.

**Comment by xai1983kbu** [comment]
Finally, I decided to don't use the method described above. 
I found one additional setting - "Force Web OAuth Reauthentication", and switched to - "YES"
https://developers.facebook.com/docs/facebook-login/reauthentication/
I think this setting will increase safety for some extend. This is enough for me, now.
![force_web_oauth](https://user-images.githubusercontent.com/14042193/83662096-c0d1a700-a5cf-11ea-92b8-3d4d158f1c6b.png)

I tested Facebook login in https://stackoverflow.com/ and some other sites, and I figured out that even popular sites don't logout from Facebook and subsequent logins via Facebook don't claim for user's password.

@saaniaki sorry for sort of spam in your issue

**Comment by wywarren** [comment]
After paying for AWS business support, the response we got so far after 40+ days is that there is no way to clear the cookie on the hosted UI domain without using the LOGOUT endpoint. We even asked if it is possible to store the cookie on the root domain instead to have other subdomains handle the clearing of the cookie. The answer we received was that it's not possible but no explanations were given. Currently the cookie set to reside on your hosted UI subdomain, if using cognito's domain it would be something along the lines of aaaa.auth.ap-southeast-1.amazoncognito.com or yoursubdomain.domain.com. Since there written to those subdomains, you wouldn't be able to clear cookies on them from other subdomains or the root domain.

Flashing the LOGOUT endpoint by opening it in a new tab and quickly closing it seems like the only solution to date.

Using a behind the scenes GET request to the LOGOUT endpoint won't work and opening it in an iframe will also be denied.

There doesn't seem to be an adequate solution for this.

**Comment by Amaanuddin** [comment]
Using the Logout endpoint by opening it in a new tab is throwing me an error saying that redirect_uri is missing.

**Comment by fernandomoraes** [comment]
After trying a few options I discovery a way that works for me. Here I want allow the users to choice the google account on every login. So what I done here is use a random value to 'customState' parameter, something like:

```.js
Auth.federatedSignIn({ provider, customState: 'randomValue' });
```

Does anyone know if there is any side effect in doing this?

Thanks.

**Comment by fernandomoraes** [comment]
@jorgexgb

**Comment by Amaanuddin** [comment]
@fernandomoraes I tried providing random value to the custom state parameter, it is not working for me.

**Comment by fernandomoraes** [comment]
@Amaanuddin are you using google?

**Comment by Amaanuddin** [comment]
@fernandomoraes  Yes

**Comment by fernandomoraes** [comment]
@Amaanuddin are you logged with more than one google account on the browser? 

for me just this code snippet works, if you want to share more about your code, maybe I can help you

**Comment by Amaanuddin** [comment]
@fernandomoraes Yes, Im logged in with more than one google account.

**Comment by Amaanuddin** [comment]
@fernandomoraes  ![image](https://user-images.githubusercontent.com/29299860/111029860-01930200-8425-11eb-9fb6-111c379cd87c.png)

**Comment by Amaanuddin** [comment]
@fernandomoraes 
![image](https://user-images.githubusercontent.com/29299860/111029899-46b73400-8425-11eb-8567-23b35337f13f.png)
provider is coming as 'Google'

**Comment by fernandomoraes** [comment]
Here I'am using:

`.js
Auth.federatedSignIn({ provider, customState: 'random' });
`
can you clean your cookies and localstorage values for test?

**Comment by Amaanuddin** [comment]
Did that, still not working

**Comment by fernandomoraes** [comment]
If you wanna see running on my application, I just published on stage, look https://stage.keepo.io

**Comment by Amaanuddin** [comment]
@fernandomoraes The problem is not with the custom state, it was with the logout URL. Now it is working, if I have multiple google accounts signed in. Thanks for your help.

**Comment by fernandomoraes** [comment]
@Amaanuddin nice, now is working even without custom state? or do you need to set this parameter?

**Comment by Amaanuddin** [comment]
@fernandomoraes it's working without the custom state parameter.

**Comment by rmi-01** [comment]
Hi guys, any progress on this issue. 
I've partially solved my problem by using this piece of code 
`window.location = https://${AUTH_DOMAIN}/logout?client_id=${cognito_client_id}&logout_uri=https://localhost:3000/register`
But, it seems to only work in Google Chrome and not in Edge, Firefox or any other browser. 
Does anybody found a proper solution for this?
Thanks!

**Comment by Amaanuddin** [comment]
@rmi-01 I have tested the code in all the browsers mentioned except safari and it's working.

**Comment by fernandomoraes** [comment]
@abhishek6498 

`Auth.federatedSignIn({ provider: 'Google', customState: 'random' });`

This is the snippet code that I am using here, I've tested with a lot of browsers.

**Comment by theogravity** [comment]
> @abhishek6498
> 
> `Auth.federatedSignIn({ provider: 'Google', customState: 'random' });`
> 
> This is the snippet code that I am using here, I've tested with a lot of browsers.

This does not work for me for google. Added a randomized string to the customState and logging out / logging back in will not prompt switching for google.

Is there another thing you need to do?

**Comment by jakebrinkmann** [comment]
This seems to work for me (using a custom federated SAML provider):

```javascript
Auth.currentAuthenticatedUser()
      .catch(() => console.warn('User is not signed in.'))
      .then((currentUser) => currentUser.signOut());
```

**Comment by nvnk3** [comment]
Will there be any progress on this? same issue with amplify_flutter as well

**Comment by tannerabread** [comment]
Related #4044

**Comment by natuan62** [comment]
4 years and no anything updates to fixed ??

**Comment by jbienesdev** [comment]
Just dropping this fix I found here. I added the url for the login page on AWS Cognito as part of the Allowed sign out URLs field. It can be found under

`App Clients > Login Pages > Edit > Allowed sign-out URLs `

![Image](https://github.com/user-attachments/assets/026cd31a-1820-4d42-a5e8-6443f5d8e4bc)

After that, when signing out the application, I updated window.location with the cognito logout url.

```javascript
const logoutUrl = `https://${process.env.VUE_APP_COGNITO_USER_POOL_DOMAIN}/logout?client_id=${process.env.VUE_APP_COGNITO_CLIENT_ID}&logout_uri=${window.location.origin}/login`;
window.location = logoutUrl;
```

`client_id` and `logout_uri` are required. It would then clear the `cognito` cookie that was injected during login. Thus, logging back in again should open the Google account selector screen.

**IMPORTANT**: `logout_uri` and the sign out URL made in cognito must match

**Comment by jbienesdev** [comment]
Just dropping this fix I found here. I added the url for the login page on AWS Cognito as part of the Allowed sign out URLs field. It can be found under

`App Clients > Login Pages > Edit > Allowed sign-out URLs `

![Image](https://github.com/user-attachments/assets/026cd31a-1820-4d42-a5e8-6443f5d8e4bc)

After that, when signing out the application, I updated window.location with the cognito logout url.

```javascript
const logoutUrl = `https://${process.env.VUE_APP_COGNITO_USER_POOL_DOMAIN}/logout?client_id=${process.env.VUE_APP_COGNITO_CLIENT_ID}&logout_uri=${window.location.origin}/login`;
window.location = logoutUrl;
```

`client_id` and `logout_uri` are required. It would then clear the `cognito` cookie that was injected during login. Thus, logging back in again should open the Google account selector screen.

**IMPORTANT**: `logout_uri` and the sign out URL set in cognito must match

**Comment by juanherrerapragma** [comment]
Still having this problem, has anyone find a clear solution?

**Comment by AllanZhengYP** [comment]
Hi @juanherrerapragma 

Can you confirm you have configured the logout URL as in https://github.com/aws-amplify/amplify-js/issues/3933#issuecomment-2592926566? Can you provide what social provider you are using? Also can you try this in a Chrome browser after logging out any Google account?

**Comment by juanherrerapragma** [comment]
Thanks for that, but it's not working
My amplifyconfiguration.json has:
{
  "aws_project_region": "us-east-1",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_Hi1xxxxxx",
  "aws_user_pools_web_client_id": "2k5qi641c8lp2vlpkbhcxxxxxx",
  "oauth": {
    "domain": "[us-east-1hi1xxxxxx.auth.us-east-1.amazoncognito.com](http://us-east-1hi1xxxxxx.auth.us-east-1.amazoncognito.com/)",
    "scope": [
      "aws.cognito.signin.user.admin",
      "email",
      "openid",
      "phone",
      "profile"
    ],
    "redirectSignIn": "http://localhost:5173/",
    "redirectSignOut": "http://localhost:5173/login",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [
    "GOOGLE"
  ],
  "aws_cognito_signup_attributes": [],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 6,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ]
} 


My logout function in authService has:
export const logout = async () => {
  try {
    await signOut({ global: true });

    const domain = '[us-east-1hi1xxxxxx.auth.us-east-1.amazoncognito.com](http://us-east-1hi1xxxxxx.auth.us-east-1.amazoncognito.com/)'; 
    const clientId = '2k5qi641c8lp2vlpkbhcxxxxxx'; 
    const logoutUri = encodeURIComponent('http://localhost:5173/'); 
    const redirectUri = encodeURIComponent('http://localhost:5173/login'); 

    const logoutUrl = `https://${domain}/logout?client_id=${clientId}&logout_uri=${logoutUri}&redirect_uri=${redirectUri}&response_type=code`;

    localStorage.clear();
    sessionStorage.clear();

    window.location.href = logoutUrl;
  } catch (error) {
    console.error('Error al cerrar sesión:', error);
  }
};

**Comment by AllanZhengYP** [comment]
Thanks @juanherrerapragma 

This issue may relates to https://github.com/aws-amplify/amplify-js/issues/4044. We will post any update we have in that thread.

**Comment by jjarvisp** [comment]
Hi everyone, I will be closing this issue in favor of #4044 to cover the account selection on subsequent sign in issue that is being described above.

At this moment, it's not possible to initiate a sign out from a social provider; users can only be signed out of the current application client session. If you wish to sign users of their session with an external identity provider you must direct them to the sign out page for that provider. [See Cognito documentation regarding the `/logout` endpoint.](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html#:~:text=The%20logout%20endpoint%20doesn%27t%20sign%20users%20out%20of%20OIDC%20or%20social%20identity%20providers%20(IdPs).%20To%20sign%20users%20out%20from%20their%20session%20with%20an%20external%20IdP%2C%20direct%20them%20to%20the%20sign%2Dout%20page%20for%20that%20provider.)
