### ISSUE TITLE
login data not saved in AsyncStorage, auth state not persisted

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#3956]
**Describe the bug**
As state [here](https://github.com/aws-amplify/amplify-js/issues/812#issuecomment-388111937), auth state is persisted using AsyncStorage - this used to work in my app but now auth state is not persisted and user is logged out every time he opens the app, `console.log`ing all keys from async storage I don't get anything from amplify, only keys that I have set myself.

**To Reproduce**
1. Create react native app
2. set up amplify
3. create log in form and log in with it
4. exit app
5. enter app again - you are logged out

**Expected behavior**
User auth state should be saved, as state in the link above it should be in AsyncStorage

**Additional context**
Something that can cause this is the fact that react-native removed the AsyncStorage module and moved it to a package called `@react-native-community/async-storage` so you may need to add this package and update your imports, everything should be the same other than that.

This is a crucial part of every application that is using authentication - users can't be expected to log in every time they open the app

**Comment by deita0x** [comment]
I have the same problem but only in ios, if I close the application or reload it I get `not authenticated` when I call the `Auth.currentAuthenticatedUser()`. In android it works as expected.

**Comment by idanlo** [comment]
@haverchuck AsyncStorage is from `react-native` and not `ionic`

**Comment by haverchuck** [comment]
@idanlo -  you're right; my mind was already in Ionic-land.  The error is corrected.

**Comment by diegocosta** [comment]
Me too, I temporary fixed it removing @react-native-community/async-storage . :(

**Comment by deita0x** [comment]
In my case I have solved it by making a copy of `StorageHelper` but using AsyncStorage from  `@ react-native-community/async-storage` instead of `react-native` and then using in this way:
```javascript
Amplify.configure({
  Auth: {
    // ...
    storage: new StorageHelper().getStorage()
  }
});
```
I think the general solution is updating that dependency [here](https://github.com/aws-amplify/amplify-js/blob/7b297422fde91e53af242108c6394dd726dc438e/packages/core/src/StorageHelper/reactnative.ts#L13) with the new package https://github.com/react-native-community/async-storage

**Comment by jpaas** [comment]
I tried the custom `StorageHelper` but for some reason it doesn't work for me. In my app it tries to call `currentAuthenticatedUser` when it launches, but that promise never returns. Doesn't resolve, doesn't reject. Nothing logged.

**Comment by markmckim** [comment]
I'm also having this issue. Can we get #3991 merged?

**Comment by Dellybro** [comment]
+1 lets get this merged.

**Comment by idanlo** [comment]
I created another issue since this one is already buried in the issues list
