### ISSUE TITLE
DataStore immediately issues UPDATE after INSERT

### ISSUE THREAD

**Issue by kevinold** [aws-amplify/amplify-js#4588]
**Describe the bug**

DataStore performs an INSERT with `name` attribute and immediately triggers UPDATE which removes `name` attribute dispite the record being persisted to DynamoDB table.

I am updating an existing Amplify project/API to use DataStore.  

I have upgraded my api using `amplify update api` (https://github.com/kevinold/gift-list-datastore/blob/master/amplify/backend/api/santaslist/transform.conf.json) and updated the `KidForm.js` and `KidList.js` components to use DataStore.

**To Reproduce**

1. Deploy application
1. Go to http://localhost:3000
1. Type name in "New Kid" form
1. Click "Add Kid" button
1. Open Chrome Dev Console and notice DataStore performs an INSERT with `name` attribute and immediately triggers UPDATE which removes `name` attribute
1. Notice record is persisted to DynamoDB table

-- or --

Link to sample code

https://github.com/kevinold/gift-list-datastore

**Expected behavior**

Update does not immediately happen after insert.

**Screenshots**
<img width="1436" alt="Screen Shot 2019-12-17 at 11 40 47 AM" src="https://user-images.githubusercontent.com/21967/71016908-d4419200-20c3-11ea-92bc-750ab5f302ea.png">

Data is persisted to DynamoDB

<img width="982" alt="Screen Shot 2019-12-17 at 11 57 01 AM" src="https://user-images.githubusercontent.com/21967/71017295-634eaa00-20c4-11ea-9a88-c3bc50bccf22.png">

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 6.62 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Brave Browser: 78.1.0.1
    Chrome: 79.0.3945.79
    Chrome Canary: 81.0.3999.0
    Firefox: 70.0.1
    Safari: 13.0.2
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3
    @aws-amplify/datastore: ^1.0.2 => 1.0.2
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.3.2 => 9.3.2
    @testing-library/user-event: ^7.1.2 => 7.1.2
    apollo-cache-inmemory: ^1.6.5 => 1.6.5
    apollo-client: ^2.6.8 => 2.6.8
    apollo-link-context: ^1.0.19 => 1.0.19
    apollo-link-http: ^1.5.16 => 1.5.16
    aws-amplify: ^2.2.0 => 2.2.0
    aws-amplify-react: ^3.1.1 => 3.1.1
    aws-appsync: ^3.0.2 => 3.0.2
    aws-appsync-auth-link: ^2.0.1 => 2.0.1
    aws-appsync-subscription-link: ^2.0.1 => 2.0.1
    cypress: 3.7.0 => 3.7.0
    eslint-plugin-cypress: ^2.7.0 => 2.7.0
    formik: ^2.0.6 => 2.0.6
    graphql-tag: ^2.10.1 => 2.10.1
    jsonwebtoken: ^8.5.1 => 8.5.1
    react: ^16.12.0 => 16.12.0
    react-apollo: ^3.1.3 => 3.1.3
    react-dom: ^16.12.0 => 16.12.0
    react-router: ^5.1.2 => 5.1.2
    react-router-dom: ^5.1.2 => 5.1.2
    react-scripts: 3.3.0 => 3.3.0
    tailwindcss: ^1.1.4 => 1.1.4
  npmGlobalPackages:
    @aws-amplify/cli: 4.6.0
    gatsby-cli: 2.8.16
    npm: 6.12.0
```

</details>

**Smartphone (please complete the following information):**

Chrome

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

https://github.com/kevinold/gift-list-datastore

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by kevinold** [comment]
cc @sebsto Would you have any ideas on why this would not be working as detailed your demo repo (https://github.com/sebsto/amplify-datastore-js-e2e)?

**Comment by kevinold** [comment]
I have narrowed this down to the `createKid` and `createGift` mutations returning an incomplete record, which seems to be what is triggering the update.

`createKid` mutation request payload (notice `name: "new kid"`)
![Screen Shot 2019-12-18 at 2 38 54 PM](https://user-images.githubusercontent.com/21967/71122967-50f96c80-21a7-11ea-90e5-faa237ebf30f.png)

`createKid` response:
![Screen Shot 2019-12-18 at 2 39 04 PM](https://user-images.githubusercontent.com/21967/71123085-7b4b2a00-21a7-11ea-8b95-f21ec9fa38c9.png)

DynamoDB "Kid" table:
![Screen Shot 2019-12-18 at 3 03 48 PM](https://user-images.githubusercontent.com/21967/71123186-bbaaa800-21a7-11ea-936a-e038082aaed2.png)

DynamoDB "AmplifyDataStore" table:
![Screen Shot 2019-12-18 at 3 06 25 PM](https://user-images.githubusercontent.com/21967/71123344-088e7e80-21a8-11ea-83b3-bc873288a5e6.png)

Console of events from subscription:
![Screen Shot 2019-12-18 at 3 08 56 PM](https://user-images.githubusercontent.com/21967/71123492-6753f800-21a8-11ea-85ed-e343afb4fe69.png)


cc @swaminator @undefobj

**Comment by elorzafe** [comment]
@kevinold 

I reproduced your problem and found a solution for it. Can you update amplify cli to the latest version and run on your project `amplify codegen models`. That should solve the issue.

**Comment by kevinold** [comment]
@elorzafe I have been using the latest version, 4.6.0 as of today.  Just to be certain, I ran `npm i -g @aws-amplify/cli@latest` and received version 4.6.0.  I ran `amplify codegen models` but there was no change in the models.  What version of amplify-cli should I install?

**Comment by kevinold** [comment]
@elorzafe I upgraded to the `"aws-amplify": "^2.2.1"` in my project and this appears to have resolved the issue without running `amplify codegen models`.  If I run that command, there is no change on my models.  Thanks for the fix!

**Comment by elorzafe** [comment]
The change was on the `schema.js` 
After I ran `amplify codegen models` it changed `"type": "string"` to `"type": "String"`

I will close this issue for now. Thanks for pointing this out!

**Comment by kevinold** [comment]
@elorzafe Odd, I've deleted my models and ran `amplify codegen models` and I still see `"type": "string"` throughout my `schema.js`, but it still works.
