### ISSUE TITLE
AuthError - not been configured correctly logged when Auth module is not imported

### ISSUE THREAD

**Issue by veproza** [aws-amplify/amplify-js#5671]
**Describe the bug**
When Auth module is not imported anywhere in project, an AuthError is logged into console, confusing newcomers
_(note that I encountered it on React Experimental brach, but I don't expect it to be a factor)_

**To Reproduce**
Create a tiny demo where `Auth` is not used, e.g.

```javascript
import React from "react";
import Amplify from "@aws-amplify/core";
import {AmplifyAuthenticator} from "@aws-amplify/ui-react";
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);

const Authenticated = (props) => {
    return (
        <AmplifyAuthenticator usernameAlias="email">
            {props.children}
        </AmplifyAuthenticator>
    );
};
export default Authenticated; // or render
```

**Expected behavior**
Console does not contain any error logs

**Code Snippet**
See above for not-working code. All it takes to get rid of the issue is to import `Auth` anywhere in the code while making sure it does not get tree-shaked for never using it, eg:
```javascript
import React, {FunctionComponent} from "react";
import Amplify from "@aws-amplify/core";
import {Auth} from 'aws-amplify';
import {AmplifyAuthenticator} from "@aws-amplify/ui-react";
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);


const Authenticated: FunctionComponent = (props) => {
    Auth.currentAuthenticatedUser(); // noop because of bug in Amplify requiring Auth is imported.
                                     // otherwise a AuthError - Amplify has not been configured correctly will be thrown
    return (
        <AmplifyAuthenticator usernameAlias="email">
            {props.children}
        </AmplifyAuthenticator>
    );
};
export default Authenticated;
```
**Screenshots**
![image](https://user-images.githubusercontent.com/1926602/80993155-e33e9c00-8e3a-11ea-8f1f-9fc134316f04.png)

**What is Configured?**
AWS Exports
   ```
const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://xxx.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-central-1:xxx",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-xxx",
    "aws_user_pools_web_client_id": "xxx",
    "oauth": {}
};
```
  
<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Memory: 1.88 GB / 15.96 GB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
  npmPackages:
    @aws-amplify/api: ^3.1.9 => 3.1.9
    @aws-amplify/datastore: ^2.0.10 => 2.0.10
    @aws-amplify/pubsub: ^3.0.10 => 3.0.10
    @aws-amplify/ui-react: ^0.2.5 => 0.2.5
    @reach/router: ^1.3.3 => 1.3.3
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.5.0 => 9.5.0
    @testing-library/user-event: ^7.2.1 => 7.2.1
    @types/jest: ^24.9.1 => 24.9.1
    @types/node: ^12.12.37 => 12.12.37
    @types/reach__router: ^1.3.5 => 1.3.5
    @types/react: ^16.9.34 => 16.9.34
    @types/react-dom: ^16.9.7 => 16.9.7
    aws-amplify: ^3.0.10 => 3.0.10
    ini: ^1.3.5 => 1.3.5
    inquirer: ^6.5.1 => 6.5.2
    node-sass: ^4.14.0 => 4.14.0
    react: 0.0.0-experimental-e5d06e34b => 0.0.0-experimental-e5d06e34b
    react-bem-helper: ^1.4.1 => 1.4.1
    react-dom: 0.0.0-experimental-e5d06e34b => 0.0.0-experimental-e5d06e34b
    react-scripts: 3.4.1 => 3.4.1
    source-map-explorer: ^2.4.2 => 2.4.2
    typescript: ^3.7.5 => 3.7.5
```

</details>

**Comment by jordanranz** [comment]
Hey @veproza, `AmplifyAuthenticator` uses the Amplify Auth category under the hood. To configure the Auth category properly you must either configure Amplify using the module in `aws-amplify`:
```
import Amplify from "aws-amplify";
import {AmplifyAuthenticator} from "@aws-amplify/ui-react";
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
```
or
```
import Auth from "@aws-amplify/auth";
import {AmplifyAuthenticator} from "@aws-amplify/ui-react";
import awsconfig from './aws-exports';

Auth.configure(awsconfig);
```

Can you point me to the documentation you are following that guides you to the broken configuration?

**Comment by Johnniexson** [comment]
I'm still stuck with this error, tried everything but not working.

**Comment by veproza** [comment]
Hi @jordanranz , I'm aware of the config, my *To reproduce* code does contain the `Amplify.configure` call.

The code itself is not from guides, it's from after I got relatively comfortable and started restructuring the app into smaller pieces. The component mentioned is supposed to be a wrapper "guarding" the inner application only for logged in users and displaying login screen for all other. But I wrote this component before needing any `Auth` methods, and the app started logging the error because of that. After adding `Auth`, the error disappeared, but I think the app should be working even without `Auth` specifically imported.

**Comment by Johnniexson** [comment]
Configuring Amplify like this, i get the AuthError:

```
import Amplify from "aws-amplify";
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);
```

But importing like this, i dont get the error.

```
import Amplify from "@aws-amplify/core";
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);
```

Any reason for this please and does it make any difference?

**Comment by veproza** [comment]
Oh I see! I imported Amplify from `@aws-amplify/core`, but I should be using `aws-amplify`! Now it works even without importing `Auth`.

This happened due to combination of IDE's automatic import and lack of correct import specification in the DataStore docs (https://docs.amplify.aws/lib/datastore/sync/q/platform/js#connect-your-app). Since I started working with Amplify using only DataStore, I couldn't find where to source `Amplify` from correctly, so I let the IDE figure it out - and it worked, for the most part, up until now.

So I'd propose adding a line `import Amplify from "aws-amplify";` to the last code example at https://docs.amplify.aws/lib/datastore/sync/q/platform/js#existing-backend, that should help some newcomers with fancy IDEs :-)

**Comment by Johnniexson** [comment]
> Oh I see! I imported Amplify from `@aws-amplify/core`, but I should be using `aws-amplify`! Now it works even without importing `Auth`.
> 
> This happened due to combination of IDE's automatic import and lack of correct import specification in the DataStore docs (https://docs.amplify.aws/lib/datastore/sync/q/platform/js#connect-your-app). Since I started working with Amplify using only DataStore, I couldn't find where to source `Amplify` from correctly, so I let the IDE figure it out - and it worked, for the most part, up until now.
> 
> So I'd propose adding a line `import Amplify from "aws-amplify";` to the last code example at https://docs.amplify.aws/lib/datastore/sync/q/platform/js#existing-backend, that should help some newcomers with fancy IDEs :-)

@veproza but i still get the error while importing from from aws-amplify like 
`import Amplify from "aws-amplify";`

**Comment by veproza** [comment]
@Johnniexson It's weird that what fixed it for me broke it for you and vice versa. Is there any minimal code example you could share? Can't it be some timing issue, that you're calling `.configure` after some other call in another module already tried to use some `Auth` method? Easiest way to check would be `console.log` something at the `Amplify.configure` line and seeing if the AuthError happens before or after that log...

**Comment by Johnniexson** [comment]
> @Johnniexson It's weird that what fixed it for me broke it for you and vice versa. Is there any minimal code example you could share? Can't it be some timing issue, that you're calling `.configure` after some other call in another module already tried to use some `Auth` method? Easiest way to check would be `console.log` something at the `Amplify.configure` line and seeing if the AuthError happens before or after that log...

@veproza  I Just tried the console log thing, the `Amplify.configure()` runs before any other thing in the app. I'm using angular on ionic.

**Comment by veproza** [comment]
@Johnniexson Sorry, that's the only thing that occurred to me. I don't know Angular or Ionic, so I won't be able to help you.

**Comment by Johnniexson** [comment]
@veproza  no probs, thanks for your time. But how any idea on diff btw configuring using Amplify from "@aws-amplify/core" and from "aws-amplify"??

**Comment by Amplifiyer** [comment]
@Johnniexson, the only difference is that importing Amplify from `aws-amplify` by default imports the Auth module and `Amplify.configure()` then successfully configure it. However importing from `@aws-amplify/core` does not do any of that.  See ref below

https://github.com/aws-amplify/amplify-js/blob/50bb84995a7b15d969f0b0ce10e6b254ec95c94b/packages/aws-amplify/src/index.ts#L18-L23

I'm looking for a fix that should make importing from `@aws-amplify/core` work as well as long as Auth is imported somewhere in your app (either through the UI-component packages such as `ui-react` or direct import in any of your other files)

**Comment by Johnniexson** [comment]
> @Johnniexson, the only difference is that importing Amplify from `aws-amplify` by default imports the Auth module and `Amplify.configure()` then successfully configure it. However importing from `@aws-amplify/core` does not do any of that. See ref below
> 
> https://github.com/aws-amplify/amplify-js/blob/50bb84995a7b15d969f0b0ce10e6b254ec95c94b/packages/aws-amplify/src/index.ts#L18-L23
> 
> I'm looking for a fix that should make importing from `@aws-amplify/core` work as well as long as Auth is imported somewhere in your app (either through the UI-component packages such as `ui-react` or direct import in any of your other files)

It works fine while importing from "@aws-amplify/core" without any error, but importing from "aws-amplify" throws the AuthError. My only problem is that i'm unsure if importing and configuring using "@aws-amplify/core" might break something else as i use other aws services such as api and storage in the app.

**Comment by jordanranz** [comment]
I am going to move this thread to a discussion.
