### ISSUE TITLE
Auth - SignUp SMS Verification Code not getting sent/delivered.

### ISSUE THREAD

**Issue by AakashPat** [aws-amplify/amplify-js#6344]
**Describe the bug**
Upon signing up with a phone number, the Verification SMS with the 6 digit code is never sent to the phone number. After trying to resend the code multiple times, the message is never received.

**To Reproduce**

1. SignUp using phone number
2. SMS not received.
3. Resend verification code.
4. No SMS received

**Expected behavior**
A SMS Verification code is sent to the phone number used during SignUp.

**Additional context**
I have already raised a Service Quota Increase ticket and have that increased. I have also explicitly set the spending limit on the SNS (Text Messaging) Console. 
I have tried using the Cognito Hosted UI to Sign Up and am facing the exact same issue with that. The verification SMS is never received.

My SNS service is working as expected as I can send out other SMS communication to our users using the aws-sdk. 

Also, if the user registers using the email address, an email is promtly sent to the user with the verification code. Only SMS are not delivered.

**Comment by shreyansjain** [comment]
+1 to this issue.

We have recently started experiencing the same issue (Spending Limit/Service Quota issues have already been resolved). 
Wanted to highlight few observations:
- Started happening start of this week (week of July 12th)
- Sending Transaction messages via AWS console works to the recipient of the OTP/MFA user
- Mostly happening this to users/phone numbers in India (Users with Canadian cell number didn't have this issue)

I have asked AWS team to confirm if it was related to recent changes due to [ILDO](https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-pinpoint-now-supports-international-long-distance-operator-ildo-routes-to-send-sms-messages-to-india/)

**Comment by AakashPat** [comment]
@shreyansjain 

Similar situation at my end.

**Comment by AakashPat** [comment]
@shreyansjain 
Similar situation at my end.


- 14 July is the first time I faced this issue.
- Sending Transaction messages via AWS SNS Console works for me too.
- My AWS Cognito Pool is based in Frankfurt (eu-central-1). During assessment, I created User Pools in other regions (us-east-1 and ap-south-1) and those User Pools are able to send verification messages just fine. Only the eu-central-1 pool is unable to send messages. (Also tried with a second and a third User Pool created in the same region; Still unable to send messages through Cognito).
- In my case, the User Pool is unable to send messages to any phone number whatsoever. I have tried with US, DE, BE phone numbers. None are receiving any SMS Verification Code whatsoever.

In order to get a faster resolution to avoid the adverse effects on business, I am seeking approval for getting a Support Plan from AWS. It will cost us 29$/month. All this for something that should be very straight forward in the first place.

**Comment by shreyansjain** [comment]
That's strange, UserPool in `ap-south-1` is the failing for me to send to IN numbers (CA/US numbers are getting delivered). 

The worst case is, this the first point of entry to our platform and if users are not able to receive verification codes, they won't be able to use the platform. 

I'll update once I hear back from them and/or please do the same.

**Comment by AakashPat** [comment]
@shreyansjain , I can understand. Same is the problem we're facing. If users can't even register, it will impact business very heavily. For now, I have paid for Developer support and have raised a ticket with AWS. I am awaiting a response from them. Will update this thread once I hear from AWS Support.

**Comment by shreyansjain** [comment]
Heard back from AWS PM:
```
I’ve reviewed the AWS account (xxx) related to the case ID you’ve provided and confirmed this customer is currently on ILDO routes. I’m unsure why SNS would be working for them but Cognito not since Cognito actually uses SNS for the sends. 

If they are facing delivery issues they should engage Premium Support team for assistance.
```

I will initiate the Premium Support team once I hear an update from you.

**Comment by AakashPat** [comment]
It has been 15 hours since the ticket and I haven't heard back from them. It is a System Impaired issue which had a 12 hour SLA. Certainly leaves a bad taste in my mouth about AWS Support.

Once I have a response, I will let you know.

**Comment by AakashPat** [comment]
@shreyansjain, Finally heard back from AWS Support after 36 hours.

> I understand that you are facing issues while using Cognito MFA as messages are not getting delivered to your users when using Frankfurth region.

As you are already aware, Cognito MFA messages are sent using SNS in the closest region[1], hence in order to investigate the issue we will need to troubleshoot from the SNS side in eu-west-1 (Cognito Userpools in eu-central-1 is currently using SNS SMS in eu-west-1 as SNS SMS was only recently released in eu-central-1).

As a common reason that causes messages to not get delivered is when the SNS spend limit is reached, I checked the SMSMonthToDateSpentUSD[2] against the Monthly spend limit and noticed that it has hit the default limit of $1.

**Comment by AakashPat** [comment]
I have now requested a SNS Sending Limit increase for eu-west-1 region. Hopefully that should resolve my issue. Will confirm once the Limit Increase has been processed.

**Comment by shreyansjain** [comment]
Thanks for updating @AakashPat 

I tried to send Cognito SMS from `ap-south-1` and the delivery still failed. 

I am pretty sure your issue will get resolved once your spending limit has been increased.

**Comment by shreyansjain** [comment]
Incidentally, I noticed, some of the MFA texts were being sent from `ap-southeast-1` (Singapore) region, even for users based in India. 
It might be better to increase spend limt for different regions.

**Comment by AakashPat** [comment]
@shreyansjain , Indeed my problem was resolved after increasing spending limits in the required region (eu-west-1 in my case).

**Comment by AakashPat** [comment]
I'm going to close this issue as it has been resolved.

**Comment by gvb26** [comment]
I am also experiencing this issue. A number of my users are not receiving the code despite the logic of my requests being fine. Ir works for some but not all. AWS support should escalate the issue, put out an update and provide documentation

**Comment by FirdousNath** [comment]
Facing same issue...it seems like a specific no has limit. I mean if user tries more than 10 times than otp is no received on 11 call.. Facing this during the  development of one of my project

**Comment by brightfuture** [comment]
+1 with this problem
my user pool is in ap-southeast-1
and i've tried to send to US and CN numbers
all failed

**Comment by anagarjunr** [comment]
looks like this issue has still not been solved yet
pool is in `ap-south-1` and SMS is not being delivered

**Comment by mikeRChambers610** [comment]
I am having the issue as well. I am in us-east-1 and sending the SMS code to us-east-1 and still not getting the code to the phone number but getting the following result from API call:

challengeParam: {…}
​​
CODE_DELIVERY_DELIVERY_MEDIUM: "SMS"
​​
CODE_DELIVERY_DESTINATION: "+*******8242"

**Comment by mikeRChambers610** [comment]
This is happening for both of my cognito user pools

**Comment by lifehetu** [comment]
I am stuck here! I am using Cognito Multi-factor authentication. The MFA verification SMS delivered just fine before the Spend limit crossed. Then I requested to increase the spending limit and subsequently updated the SNS configuration accordingly.

Even after all this done the verification SMS is still not delivering.

The AWS team is denying any help. Asking me to go for a paid customer support.

If you have found a way out of this mess, request you to please post your solution here.

My User pools are in Mumbai reason and the SMS messages are to be sent to the users in this region itself.
Also, I created a User Pool in the Singapore region only to see the SMS messages not delivering for this region also.

With this much uncertainty and lack of support/documentation, I am not sure if I should use it in my production environment at all. Please help!

Thanks,
Puneet

**Comment by nagarjun-aample** [comment]
@lifehetu 
Since you are in `ap-south-1` region, you need to increase the spend limit in `eu-west-1`, `ap-southeast-1` regions, as suggested above. This worked for us. 
Maybe you need to increase in other regions as well (I am not quite sure about this though)
Additionally, provide IAM permissions accordingly where necessary.

This approach worked for us.

PS: In my personal opinion, I think Cognito has to undergo significant improvements for developers/businesses to confidently use it in production. Major areas of improvement being documentation, community support, flexibility (being to able edit certain details which would otherwise require deleting the cognito and re-creating it with the desired setting), more features, among others

**Comment by lifehetu** [comment]
@nagarjun-aample 
Increasing Spend Limit for the Singapore region did help. Thank you very much!

The only reason I am considering using Cognito is its HIPAA compliance. What other options do you suggest?

Thanks!

**Comment by mikeRChambers610** [comment]
For me the issue was that my verification codes were getting rejected by most phones as spam. This was fixed by registering for a 10 DLC via the pinpoint dashboard. This allows you to get a 10 digit phone number which amazon gets registered with the phone carriers and carrier will not label it as spam. Amazon then uses this new 10DLC by default if using Cognito. Hope it helps.
