### ISSUE TITLE
AmplifySignUp and AmplifyConfirmSignUp submit buttons stay enabled while submitting

### ISSUE THREAD

**Issue by MahsaMaslahati** [aws-amplify/amplify-js#7032]
**Describe the bug**
I'm using the `@aws-amplify/ui-react` components, with specific `formFields`. We have `PreSignup` and `PostConfirmation` lambdas which check and do something, so it takes a bit longer to create and confirm the user. When submitting the AmplifySignUp and AmplifyConfirmSignUp pages, the submit buttons stay enabled and the user can have multiple clicks and sometimes create multiple users when signing up!

**To Reproduce**
Use AmplifyAuthenticator in your app

**Expected behavior**
The submit button must disappear and a circularProgress should appear to prevent multiple clicks on the button

**Code Snippet**
```
import { AmplifyAuthenticator, AmplifySignIn, AmplifySignUp } from "@aws-amplify/ui-react"

export const Authenticator = React.memo(() => {
  return (
    <AmplifyAuthenticator usernameAlias="email">
        <AmplifySignIn
          headerText="Sign In to your Account"
          slot="sign-in"
          usernameAlias="email"
        />
      <AmplifySignUp
          slot="sign-up"
          usernameAlias="email"
          formFields={[
            ...some fields
          ]}
        />
   </AmplifyAuthenticator>
)
})
```

**Comment by harrysolovay** [comment]
I see you're not adding any second argument to `React.memo`. The second argument is usually a prop-equality-checking function. Otherwise, React has little ability to check between renders if there are changes / whether to re-compute the UI. Please remove the `React.memo` wrapping and let us know if the disabled-UI change takes effect.

**Comment by MahsaMaslahati** [comment]
Hi @harrysolovay , thank you for your reply. I just removed the `React.memo` wrapping and tested the SignUp and ConfirmSignUp process, the same happened and it did not solve the problem.

I actually ended up developing custom components in my project. In order to do that I've been checking the code of components [amplify-confirm-sign-up](https://github.com/MahsaMaslahati/amplify-js/blob/bbe97b1054da4eb13459ca054fa1cbfe8b857b82/packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx) and [amplify-sign-up](https://github.com/MahsaMaslahati/amplify-js/blob/bbe97b1054da4eb13459ca054fa1cbfe8b857b82/packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx) and realized what was causing the problem, so I pushed a [commit](https://github.com/MahsaMaslahati/amplify-js/commit/bbe97b1054da4eb13459ca054fa1cbfe8b857b82) hoping it would solve the issue. I would really appreciate it if you could take a look at it.

Thank you for your time.

**Comment by sammartinez** [comment]
Thanks for contributing @MahsaMaslahati! I will see if we can have one of our team members look at the pull request.

**Comment by MahsaMaslahati** [comment]
Thank you @sammartinez . I'm not sure if it's still valid though. I think the problem has been solved with the new update!

**Comment by ErikCH** [comment]
I was testing this again today, and I was able to see a loading spinner after clicking the 'Create Account' button, which prevented further clicks. I'll set this pending to be closed unless it's still occurring.

**Comment by MahsaMaslahati** [comment]
Thank you @ErikCH . Yes, it's not occurring anymore thanks to the new updates.
