### ISSUE TITLE
BUG "The security token included in the request is invalid. (Service: DynamoDb, Status Code: 400, Request ID…"

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-js#7046]
**Describe the bug**
I am getting this error intermittently when loading data using graphql - the code is running a loop and seems to randomly fails with this error.  

**Amplify CLI Version**
4:30.0

**To Reproduce**
Not sure if this is reproducible

**Expected behavior**
I wouldn't expect random failure when processing data items in a loop.

**Desktop (please complete the following information):**
 - OS: macOS10.15.7
 - Node Version: v12.18.1

**Additional context**
This seems to be a new issue that has started occurring

**Sample Code**

```
export const loadSessionTypeCodes = async () => {

  const results = await API.graphql({ query: customQueries.listSessionTypes });
  // console.log("results.data.listSessionTypes.items: " + results.data.listSessionTypes.items.length)
  console.log("listSessionTypes", results.data.listSessionTypes.items)

  if (results.data.listSessionTypes.items.length > 0) {
    return results.data.listSessionTypes.items.sort(function (a, b) { return a.name > b.name })
  }

  for (const item of sCodesInput) {
    console.log("item: " + item.name)
    try {
      const newCodeResult = await API.graphql({
        query: mutations.createSessionType, variables: {
          input: { name: item.name }
        }
      });

      const newCode = newCodeResult.data.createSessionType

      // Load activity types
      for (const subitem of item.activityTypes) {
        console.log("subitem: " + subitem.name)
        console.log("newSessionType.id: " + newCode.id)
        try {
          const newSubcode = await API.graphql({
            query: mutations.createActivityType, variables: {
              input: { name: subitem.name, activityTypeSessionTypeId: newCode.id }
            }
          });
        } catch (err) {
          console.log("error creating ActivityType codes", err)
        }

      }

      // Load modes
      for (const subitem of item.modes) {
        // console.log("subitem: " + subitem.name)
        // console.log("newSessionType.id: " + newCode.id)
        try {
          const newSubcode = await API.graphql({
            query: mutations.createMode, variables: {
              input: { name: subitem.name, modeSessionTypeId: newCode.id }
            }
          });
        } catch (err) {
          console.log("error creating Modes codes", err)
        }

      }

    } catch (err) {
      console.log("error creating SessionType codes", err)
    }

  }

  const listresults = await API.graphql({ query: customQueries.listSessionTypes });
  // console.log("listresults.data.listSessionTypes.items")
  // console.log(listresults.data.listSessionTypes.items)
  return listresults.data.listSessionTypes.items.sort(function (a, b) { return a.name > b.name })
}
```

** Additional information **
If I change the code to use graphqlOperation this error seems to go away - is there an explanation for this ?

```
export const loadSessionTypeCodes = async () => {

  const results = await API.graphql({ query: customQueries.listSessionTypes });
  // console.log("results.data.listSessionTypes.items: " + results.data.listSessionTypes.items.length)
  console.log("listSessionTypes", results.data.listSessionTypes.items)

  if (results.data.listSessionTypes.items.length > 0) {
    return results.data.listSessionTypes.items.sort(function (a, b) { return a.name > b.name })
  }

  for (const item of sCodesInput) {
    console.log("item: " + item.name)
    try {
      const newCodeResult = await API.graphql(graphqlOperation(mutations.createSessionType, {
          input: { name: item.name }
        }));

      const newCode = newCodeResult.data.createSessionType

      // Load activity types
      for (const subitem of item.activityTypes) {
        console.log("subitem: " + subitem.name)
        console.log("newSessionType.id: " + newCode.id)
        try {
          const newSubcode = await API.graphql(graphqlOperation(mutations.createActivityType, {
              input: { name: subitem.name, activityTypeSessionTypeId: newCode.id }
            }
          ));
        } catch (err) {
          console.log("error creating ActivityType codes", err)
        }

      }

      // Load modes
      for (const subitem of item.modes) {
        // console.log("subitem: " + subitem.name)
        // console.log("newSessionType.id: " + newCode.id)
        try {
          const newSubcode = await API.graphql(graphqlOperation(mutations.createMode, {
              input: { name: subitem.name, modeSessionTypeId: newCode.id }
            }
          ));
        } catch (err) {
          console.log("error creating Modes codes", err)
        }

      }

    } catch (err) {
      console.log("error creating SessionType codes", err)
    }

  }

  const listresults = await API.graphql({ query: customQueries.listSessionTypes });
  // console.log("listresults.data.listSessionTypes.items")
  // console.log(listresults.data.listSessionTypes.items)
  return listresults.data.listSessionTypes.items.sort(function (a, b) { return a.name > b.name })
}
```

**Comment by amhinson** [comment]
@duncangroenewald I'm thinking that using `graphqlOperation` isn't actually changing the behavior here, since it is just a simple [passthrough](https://github.com/aws-amplify/amplify-js/blob/main/packages/api-graphql/src/GraphQLAPI.ts#L35-L38).

Would you be able to provide a more concise reproduction sample that we could replicate on our end?

**Comment by duncangroenewald** [comment]
@amhinson  sure I can put the old code back and replicate this.

**Comment by duncangroenewald** [comment]
@amhinson - I have not been able to reproduce this yet, but there are another 5 or 6 functions like the one above that I might need to be converted back to see whether that recreates the problem.

**Comment by nat-n** [comment]
Encountering the same issue under similar conditions presently with a stack I just deployed via amplify 4.32.1

I'm using Cognito user pool based auth, though the error kind of makes it sound like AppSync is sometimes randomly failing to authenticate with DynamoDB.

**Comment by t-lm** [comment]
Same issue here... Random fails after stack update. Issue seems to disappear after 15-30 minutes

**Comment by darlinj** [comment]
Same issue here.  I don't think this is an Amplify problem as I have seen it when using the appsync console to run queries against my API.  My API wasn't created using Amplify wizard.

**Comment by alxistn** [comment]
Up I'm having the same issue here

**Comment by dhyeyshah** [comment]
I am still facing this exact issue. Any updates on this front?

**Comment by kaxax** [comment]
For me issue started when I delete and recreate some table on amplify schema several times. after a few minutes issue disappeared on its own. I think appsync was trying to connect a new table with old (deleted same-named table) credentials. after few minutes it's started to use new credentials and the issue disappeared. does anyone experience this issue for more than several minutes?
