### ISSUE TITLE
Error: File size does not match between local file and file on s3 when using Storage.put() resumable=true

### ISSUE THREAD

**Issue by sqnfsa** [aws-amplify/amplify-js#9857]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, Storage

### Amplify Categories

storage

### Environment information

<details>

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 831.74 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 97.0.2
    Safari: 15.3
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/material: ^5.6.3 => 5.6.3 
    @testing-library/jest-dom: ^5.16.4 => 5.16.4 
    @testing-library/react: ^13.1.1 => 13.1.1 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^4.3.20 => 4.3.20 
    filesize: ^8.0.7 => 8.0.7 
    react: ^18.1.0 => 18.1.0 (17.0.2)
    react-dom: ^18.1.0 => 18.1.0 
    react-scripts: 5.0.1 => 5.0.1 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 8.1.0
    corepack: 0.10.0
    electron: 16.0.6
    npm: 8.6.0

```

</details>

### Describe the bug

I am building an authenticated file transfer service using Amplify. 

User journey: 
1. User visits a URL
2. User gets authenticated using a username/password using Amplify Auth
3. User selects a local file via HTML file input of type File
4. User is shown upload progress using `progressCallback(progress)`
5. Amplify uses the Storage method to upload the file in chunks (resumable=true). The file ends up in the `private` folder (uploader has access to their own files only)
6. Amplify Put() triggers completeCallback(event):

```json
{
  key: '{username}/Big_Buck_Bunny_1080_10s_30MB.mp4'
}
```

At the end of the upload, the browser throws the following error in the console:

```
Uncaught (in promise) Error: File size does not match between local file and file on s3
    at AWSS3UploadTask.<anonymous> (AWSS3UploadTask.ts:375:1)
    at step (AWSS3ProviderManagedUpload.ts:346:1)
    at Object.next (AWSS3ProviderManagedUpload.ts:346:1)
    at fulfilled (AWSS3ProviderManagedUpload.ts:346:1)
```

It looks like the following condition is failing within AWSS3UploadTask:

```javascript
const valid = Boolean(obj && obj.Size === this.file.size);
		if (!valid) {
			throw new Error(
				'File size does not match between local file and file on s3'
			);
		}
```

File attributes:

```javascript
console.log(e.target.files[0])

//outputs
{
    lastModified: 1615872273620
    lastModifiedDate: Tue Mar 16 2021 16:24:33 GMT+1100 (Australian Eastern Daylight Time) {}
    name: "Big_Buck_Bunny_1080_10s_30MB.mp4"
    size: 30704510
    type: "video/mp4"
    webkitRelativePath: ""
}

```

The final API call Storage.put() makes is to grab the uploaded file from S3 and compare its filesize with the local/source file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <Name>{bucket_name}</Name>
   <Prefix>private/{uuid}/{username}/Big_Buck_Bunny_1080_10s_30MB.mp4</Prefix>
   <KeyCount>1</KeyCount>
   <MaxKeys>1000</MaxKeys>
   <IsTruncated>false</IsTruncated>
   <Contents>
      <Key>private/{uuid}/{username}/Big_Buck_Bunny_1080_10s_30MB.mp4</Key>
      <LastModified>2022-05-02T00:32:54.000Z</LastModified>
      <ETag>"392e1df2a35bb53afc40eab21c3309b8-6"</ETag>
      <Size>30704510</Size>
      <StorageClass>STANDARD</StorageClass>
   </Contents>
</ListBucketResult>

```

The file sizes look the same so not sure why an exception is being thrown. Also not sure why the exception is uncaught when Auth.put() is wrapped in try/catch.

Tested in Chrome Version 100.0.4896.88 (Official Build) (x86_64) on MacOS

### Expected behavior

There shouldn't be a file mismatch error thrown when file sizes match. 

### Reproduction steps

1. Setup Amplify project
2. Add auth 
3. Add storage (CREATE_AND_UPDATE", "READ)
4. Set storage level to private (in index.js of the React app)
```javascript
Storage.configure({
  level: "private",
});
```

Tested both locally and with amplify hosting. 

### Code Snippet

```javascript
  async function onFileSelection(e) {
    const file = e.target.files[0];
    console.log("file attributes", file);
    const loggedInUser = await Auth.currentAuthenticatedUser();
    try {
      const upload = await Storage.put(
        `${loggedInUser.username}/${file.name}`,
        file,
        {
          resumable: true,
          progressCallback(progress) {
            // call progress state fn
            setUploadProgress(
              `Uploaded: ${filesize(progress.loaded)}/${filesize(
                progress.total
              )}`
            );
          },
          completeCallback: (event) => {
            console.log(`Successfully uploaded`, event);
          },
        }
      );
      console.log(upload);
    } catch (error) {
      console.log("Error uploading file: ", error);
    }
  }
```

Total bytes logged by `console.log(upload);` shows `totalBytes: 30704510`

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by stocaaro** [comment]
Auto-closed when I merged the fix. Reopening pending the weekly release.

**Comment by abdallahshaban557** [comment]
Closing this since fix has been released https://github.com/aws-amplify/amplify-js/pull/9763

**Comment by tannerabread** [comment]
@lorenzyannick it seems this was [difficult to reproduce before ](https://github.com/aws-amplify/amplify-js/pull/9763#pullrequestreview-1210337828). 

Do you think you can provide different steps than the OP on how to reproduce this consistently? 
Can you also add your package.json as it currently stands when seeing this bug

**Comment by lorenzyannick** [comment]
You can test with @sqnfsa code.


_verifyFileSize call 
_listSingleFile which return undefined

_listSingleFile call ListObjectsV2Command
But this.prefixPromise return "public/" and I'm in private.


I've found somewhere :

```
var prefixPromise = Credentials.get().then(function(credentials) {
        var cred = Credentials.shear(credentials);
        return getPrefix(__assign62(__assign62({}, config), { credentials: cred }));
      });
      var task = new AWSS3UploadTask({
        s3Client,
        file,
        emitter,
        level: config.level,
        storage: this._storage,
        params,
        prefixPromise
      });
      ```

But my knowledge stops here

Is that clear ?

**Comment by charlieforward9** [comment]
This issue is still present. It is most apparent with image files.

**Comment by abdallahshaban557** [comment]
Hi @charlieforward9  - can we please create a new Github issue for us to track this? We want to make sure we have all the reproduction steps to further validate this.

**Comment by charlieforward9** [comment]
Nevermind, I just made the silliest mistake that took 10 hours to find........... 

Appreciate you guys for being supportive and rapid to respond.

**Comment by charlieforward9** [comment]
My mistake was that I was trying to save multiple different files with the same path, so clearly, the file at the path in the S3 is not the same size as the local.

It would be valuable to log a warning that a file is going to be overwritten.

**Comment by ravij3** [comment]
Been seeing this issue recently and @lorenzyannick 's solution worked for me but I have no idea why.  Could someone please explain 
1. What is the difference between different levels and 
2. Why not setting levels alters the original file size as pointed out by the error?

Much appreciated!

**Comment by stocaaro** [comment]
@ravij3 ,

Maybe I'm misunderstanding, but the private/protected/public access levels are different contexts / scopes in which your files can be saved. I would expect giving the same name to different files under these different levels would result in them being different sizes, right?

It seems likely that I'm misunderstanding the situation your describing. Can you help me understand your situation better?

As Abdallah mentioned above, with more detail, your issue may be better addressed as a [new issue](https://github.com/aws-amplify/amplify-js/issues/new/choose) with a link back to this one rather than continuing the conversation / investigation here.

Thanks,
Aaron

**Comment by ravij3** [comment]
@stocaaro 

In my case it turned out that I had set public prefix to empty while configuring Amplify.

```
Storage: {
            region: config.region,
            identityPoolId: config.identityPoolId,
            bucket: config.bucket,
            customPrefix: {
                public: "",
            },
        },
```

When I was performing the Storage.put without specifying the level in my code, by default the files would end up in the
"public/" folder in my S3 bucket. For some reason the config that I have setup is not being used while making the put call.

```
Storage.put(key, f, {
            metadata,
            resumable: true,
            progressCallback: (progress: ProgressCallbackArgs) => {
                ..
            },
            completeCallback: (event: any) => {
                ...
            },
            errorCallback: (event: any) => {
                ...
            },
        });
    });
```


The working solution for me was to specify the same customPrefix while making the Storage.put call

```
Storage.put(key, f, {
            metadata,
            resumable: true,
            customPrefix: {
                public: "",
            },
            progressCallback: (progress: ProgressCallbackArgs) => {
                ..
            },
            completeCallback: (event: any) => {
                ...
            },
            errorCallback: (event: any) => {
                ...
            },
        });
    });
```
